### ISSUE TITLE
Existing META-INF/services Files are Garbled

### ISSUE THREAD

**Issue by peblair** [c0d3d/easy-plugins#6]
When running `easy-plugins`, any existing `META-INF/services` files that `easy-plugins` tries to update have all newlines removed.
(fix is to add `writer.write('\n')` after [this line](https://github.com/c0d3d/easy-plugins/blob/fd7630947e68cc08c242ca410e08ce448f387348/core/src/main/java/com/nlocketz/internal/Util.java#L118))

**Comment by c0d3d** [comment]
https://github.com/c0d3d/easy-plugins/commit/0dc801621fbe8078d72bc1791542445923fab596
